### ISSUE TITLE
Daze.js cook book

### ISSUE THREAD

**Issue by czewail** [dazejs/daze#1]
features suggest here

大家有什么功能建议可以在这里提出

**Comment by IceMimosa** [comment]
楼主有roadmap计划么，我想用这个搞个装修系统，之前用的nest。

**Comment by czewail** [comment]
@IceMimosa 目前还没有 roadmap，不过目前有一些模块的开发计划：

- model (开发中)
- websocket
- doubbo

**Comment by IceMimosa** [comment]
从我目前的使用感受，我提几个观点哈：
1. 感觉使用注解的方式的更优雅些，而不是使用继承的方式。比如类spring语义：@Controller，@Service, @Repository等。我看项目把 @useService 去掉了，是准备使用类似 @Inject 的方式吗
2. 以插件（middleware、starter等）的方式提供额外的三方功能。比如以后集成rpc或者orm之类的，避免framework层太臃肿。这点感觉nest维护的挺好
3. 更多的samples
4. 另外感觉项目很棒，想参与一起开发，现在是有在生产使用了嘛？

**Comment by czewail** [comment]
1 由于注解目前的实现是动态的对于类型提示不是很友好，准备在 stage-3的提案实现后迁移过去，useService 可以直接使用 inject 实现，
2 目前已经有插件的形式 provider 不过常用的模块会集成在framework中 rpc等不是很常用的会抽成第三方包
4 目前生产环境有在用 不过部分模块比如 db 并没有使用，会逐渐在生产环境推开
4 欢迎加入开发 稍后我邀请你加入组织

**Comment by IceMimosa** [comment]
🙏好的，感谢。
