### ISSUE TITLE
关于注入装饰器的设计

### ISSUE THREAD

**Issue by czewail** [dazejs/daze#230]
@IceMimosa 

你觉得使用不同的装饰器 `@useService`, `@useResource` 区分注入还是 统一 `@inejct` 注入比较好

第一种：
各个模块使用 `@service(name)` `@reource(name)` 命名的时候不会冲突

第二种：
存在命名唯一性，例如 service 模块和 resource 模块不能重名

**Comment by IceMimosa** [comment]
@czewail 

我觉得一般Controller、Service、Repository、Component等这种由`容器`统一维护的，用`@inject`就行。
Resource也是一种特殊的Bean吧，所有统一`@inject`就行。
